DATABASE_SERVER: "localhost"
DATABASE_PORT: "5432"
DATABASE_NAME: "wheels_away_iam"
DATABASE_USER: "postgres"
DATABASE_PASSWORD: "root"
DATABASE_LOG_LEVEL: "info"
DATABASE_SSL_MODE: "prefer"
API_PORT: 7000
ENV: "development"
LOG_LEVEL: "debug"
ZITADEL_URL: "localhost:8082"
ZITADEL_ISSUER: "http://localhost:8082"
ZITADEL_PROJECT_ID: "245155743534153731"
GRPC_PORT: 8000
