DATABASE_SERVER:
DATABASE_PORT:
DATABASE_NAME:
DATABASE_USER:
DATABASE_PASSWORD:
DATABASE_LOG_LEVEL:
DATABASE_SSL_MODE:
API_PORT:
ENV:
ZITADEL_URL:
ZITADEL_ISSUER:
ZITADEL_SCOPES:
ZITADEL_PROJECT_ID:
ZITADEL_JWT_KEY:
GRPC_PORT:
